#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")/.."
echo "LOCKED hidden-id-n5-nobr $(date -u +%Y-%m-%dT%H:%M:%SZ)" > MAIN-BENCH-LOCK.txt
export TIENLEN_FREEZE=v94 TIENLEN_CHALLENGER_FREEZE=v94
export TIENLEN_FREEZE_DIFF=grandmaster TIENLEN_V8_DIFF=grandmaster
export TIENLEN_BENCH_GAMES=5 TIENLEN_TARGET=0.0 TIENLEN_BENCH_SEED=20260711
export TIENLEN_FREEZE_MS=100 TIENLEN_FREEZE_ITERS=50 TIENLEN_FREEZE_SIMS=100
export TIENLEN_V8_MS=200 TIENLEN_V8_ITERS=100 TIENLEN_V8_SIMS=200
export TIENLEN_BR=0 TIENLEN_EXPLOIT=0 TIENLEN_SOFT_SAMPLES=0
export TIENLEN_LOG_GAMES=1 TIENLEN_PROGRESS_EVERY=1
export TIENLEN_BENCH_OUT=v94-identity-hidden-n5-nobr.json TIENLEN_SCRATCH=evolve
exec node evolve/bench-ladder.js
